#include "enums.h"

std::string E::VALUES[SIZE] =
{

    "APOD JSON data",
    "APOD Welcome image",
    "opportunity",
    "curiosity",
    "spirit",
    "FHAZ",
    "RHAZ",
    "MAST",
    "CHEMCAM",
    "MAHLI",
    "MARDI",
    "NAVCAM",
    "PANCAM",
    "MINITES",
    "Curiosity FHAZ data",
    "Curiosity RHAZ data",
    "Curiosity MAST data",
    "Curiosity CHEMCAM data",
    "Curiosity MAHLI data",
    "Curiosity MARDI data",
    "Curiosity NAVCAM data",
    "Curiosity FHAZ photos",
    "Curiosity RHAZ photos",
    "Curiosity MAST photos",
    "Curiosity CHEMCAM photos",
    "Curiosity MAHLI photos",
    "Curiosity MARDI photos",
    "Curiosity NAVCAM photos",
    "Opportunity FHAZ data",
    "Opportunity RHAZ data",
    "Opportunity NAVCAM data",
    "Opportunity PANCAM data",
    "Opportunity MINITES data",
    "Opportunity FHAZ photos",
    "Opportunity RHAZ photos",
    "Opportunity NAVCAM photos",
    "Opportunity PANCAM photos",
    "Opportunity MINITES photos",
    "Spirit FHAZ data",
    "Spirit RHAZ data",
    "Spirit NAVCAM data",
    "Spirit PANCAM data",
    "Spirit MINITES data",
    "Spirit FHAZ photos",
    "Spirit RHAZ photos",
    "Spirit NAVCAM photos",
    "Spirit PANCAM photos",
    "Spirit MINITES photos"
};
