#include "enums.h"

std::string E::VALUES[SIZE] =
{

    "APOD JSON data",
    "APOD Welcome image",
    "opportunity",
    "curiosity",
    "spirit",
    "FHAZ",
    "RHAZ",
    "MAST",
    "CHEMCAM",
    "MAHLI",
    "MARDI",
    "NAVCAM",
    "PANCAM",
    "MINITES",
    "Curiosity FHAZ",
    "Curiosity RHAZ",
    "Curiosity MAST",
    "Curiosity CHEMCAM",
    "Curiosity MAHLI",
    "Curiosity MARDI",
    "Curiosity NAVCAM",
    "Curiosity FHAZ photos",
    "Curiosity RHAZ photos",
    "Curiosity MAST photos",
    "Curiosity CHEMCAM photos",
    "Curiosity MAHLI photos",
    "Curiosity MARDI photos",
    "Curiosity NAVCAM photos",
    "Opportunity FHAZ",
    "Opportunity RHAZ",
    "Opportunity NAVCAM",
    "Opportunity PANCAM",
    "Opportunity MINITES",
    "Opportunity FHAZ photos",
    "Opportunity RHAZ photos",
    "Opportunity NAVCAM photos",
    "Opportunity PANCAM photos",
    "Opportunity MINITES photos",
    "Spirit FHAZ",
    "Spirit RHAZ",
    "Spirit NAVCAM",
    "Spirit PANCAM",
    "Spirit MINITES",
    "Spirit FHAZ photos",
    "Spirit RHAZ photos",
    "Spirit NAVCAM photos",
    "Spirit PANCAM photos",
    "Spirit MINITES photos"
};
